### Create a lecture
POST http://localhost:3010/lecture/create
content-type: application/json

{
    "title": "강의 1",
    "description": "테스트용 강의 1번 입니다!"
}

### Approve an existing lecture
PATCH http://localhost:3010/lecture/update
content-type: application/json

{
    "approved": false
}

### Query Param Test
GET http://localhost:3010/reports?~~~

### For Dummy Data
POST http://localhost:3010/lecture/create
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI5ODk3NzMwfQ.DKpIVM4jDZApjDYP77RTVli8AeAiF3x4hZzZKC-f7BE
content-type: application/json

{
    "title": "[C++과 언리얼로 만드는 MMORPG 게임 개발 시리즈] Part1: C++ 프로그래밍 입문",
    "thumbnail":"https://cdn.inflearn.com/public/courses/326162/cover/fe5368b1-e25b-4f7c-a670-b775f9e429c6",
    "description": "테스트용 강의 1번 입니다!",
    "teacherId": 1
}

### For Dummy Data
POST http://localhost:3010/lecture/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI5ODk3NzMwfQ.DKpIVM4jDZApjDYP77RTVli8AeAiF3x4hZzZKC-f7BE

{
    "title": "UIKit - iOS14 실무 가이드 <iOS앱 진짜 개발자 되기>",
    "thumbnail":"https://cdn.inflearn.com/public/courses/327148/cover/f14566b3-1845-48ee-af5f-86555dd273a4/327148-eng.png",
    "description": "테스트용 강의 2번 입니다!",
    "teacherId": 2
}

### For Dummy Data
POST http://localhost:3010/lecture/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI5ODk3NzMwfQ.DKpIVM4jDZApjDYP77RTVli8AeAiF3x4hZzZKC-f7BE

{
    "title": "엑셀 시작하기 : EXCEL 입문(Inflearn Original)",
    "thumbnail":"https://cdn.inflearn.com/public/courses/326489/cover/6bc2da6b-d7a9-46f9-932c-46cf8deba0af",
    "description": "테스트용 강의 3번 입니다!",
    "teacherId": 3
}

### For Dummy Data
POST http://localhost:3010/lecture/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI5ODk3NzMwfQ.DKpIVM4jDZApjDYP77RTVli8AeAiF3x4hZzZKC-f7BE

{
    "title": "비전공자를 위한 개발자 취업 올인원 가이드 [통합편]",
    "thumbnail":"https://cdn.inflearn.com/public/courses/326354/cover/1d6f78c0-86a5-4585-b7f5-49d57582e964",
    "description": "테스트용 강의 4번 입니다!",
    "teacherId": 4
}