### Create a lecture
POST http://localhost:3010/lecture/create
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjMwMzk3OTM5fQ.FPuVHj07kCzTNk6TmjfMU_ACsR3PcM6WTAEVEJoIQnY
content-type: application/json

{
    "title": "강의 1",
    "description": "테스트용 강의 1번 입니다!",
    "teacherId": 6,
    "videos": [{
        "url" : "https://player.vimeo.com/video/587581144?h=e542768ad0",
        "title" : "1강 : 소개"
    },{
        "url" : "https://player.vimeo.com/video/587581144?h=e542768ad0",
        "title" : "2강 : 도입부"
    },{
        "url" : "https://player.vimeo.com/video/587581144?h=e542768ad0",
        "title" : "3강 : 마무리"
    }]
}

### Approve an existing lecture
PATCH http://localhost:3010/lecture/update
content-type: application/json

{
    "approved": false
}

### Read All Lectures
GET http://localhost:3010/lecture/all

### Read Lecture By Id
GET http://localhost:3010/lecture/guest/7

### Read Lecture By Id with Token
GET http://localhost:3010/lecture/8
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNjMwMTk2OTM2fQ.ksyoLxYPpRhfyhC6h4XjzQRExmr_kUk8T3om7xuQ8Lc

### Read All Lectures Of User
GET http://localhost:3010/lecture
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTYzMDA0OTcyNH0.Z0yAkc_d-wVAWZjlHfEV22m_magcm1lVgxToaeXcyOU

### Register Lecture
PUT http://localhost:3010/lecture/8
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjMwMjEzMDA1fQ.2yMcYBreV3FhG9aqk0qS0NqpA6ySBcxzi6uevo1FQNY

### Approve Lecture
PUT http://localhost:3010/lecture/admin/3?userId=15
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTYzMDI4MjcwM30.Thl7zfBnvmEhyxl6KFGr7z2yv8mswM1DyVGSDcx3GFY

### Register Review
PUT http://localhost:3010/lecture/review/2
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksImlhdCI6MTYzMDI4MzI1Nn0.7t5FKgVZ3w-qV-NxyVb-Ya3CGTUP6o2g18N3ZKYsE38
content-type: application/json

{
    "review" : "정말 좋은 강의입니다!",
    "rating" : 5
}

### Get Recent Reviews
GET http://localhost:3010/lecture/review

### Create Tag
POST http://localhost:3010/lecture/tag/create
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjMwMTc0MTU3fQ.prDHDjF_4yZNRiEQS7W1TIjhJL533UQlDsac_0TTBrc
content-type: application/json

{
    "name" : "테스트"
}

### Read All Tags
GET http://localhost:3010/lecture/tag/all
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjMwMTc0MTU3fQ.prDHDjF_4yZNRiEQS7W1TIjhJL533UQlDsac_0TTBrc

### Read All Tags Of Lecture
GET http://localhost:3010/lecture/tag/5

### Connect Tag with Lecture
PUT http://localhost:3010/lecture/tag/7?ids=13
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjMwMTc0MTU3fQ.prDHDjF_4yZNRiEQS7W1TIjhJL533UQlDsac_0TTBrc






### For Dummy Data
POST http://localhost:3010/lecture/create
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTYyOTk1NDUwMn0.ipfoU53a29vMJX34gL3wAZ-42op7LSTV9t-l5rE8GIQ
content-type: application/json

{
    "title": "[C++과 언리얼로 만드는 MMORPG 게임 개발 시리즈] Part1: C++ 프로그래밍 입문",
    "thumbnail":"https://cdn.inflearn.com/public/courses/326162/cover/fe5368b1-e25b-4f7c-a670-b775f9e429c6",
    "description": "테스트용 강의 1번 입니다!",
    "teacherId": 14
}

### For Dummy Data
POST http://localhost:3010/lecture/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTYyOTk1NDUwMn0.ipfoU53a29vMJX34gL3wAZ-42op7LSTV9t-l5rE8GIQ

{
    "title": "UIKit - iOS14 실무 가이드 <iOS앱 진짜 개발자 되기>",
    "thumbnail":"https://cdn.inflearn.com/public/courses/327148/cover/f14566b3-1845-48ee-af5f-86555dd273a4/327148-eng.png",
    "description": "테스트용 강의 2번 입니다!",
    "teacherId": 16
}

### For Dummy Data
POST http://localhost:3010/lecture/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTYyOTk1NDUwMn0.ipfoU53a29vMJX34gL3wAZ-42op7LSTV9t-l5rE8GIQ

{
    "title": "엑셀 시작하기 : EXCEL 입문(Inflearn Original)",
    "thumbnail":"https://cdn.inflearn.com/public/courses/326489/cover/6bc2da6b-d7a9-46f9-932c-46cf8deba0af",
    "description": "테스트용 강의 3번 입니다!",
    "teacherId": 17
}

### For Dummy Data
POST http://localhost:3010/lecture/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTYyOTk1NDUwMn0.ipfoU53a29vMJX34gL3wAZ-42op7LSTV9t-l5rE8GIQ

{
    "title": "비전공자를 위한 개발자 취업 올인원 가이드 [통합편]",
    "thumbnail":"https://cdn.inflearn.com/public/courses/326354/cover/1d6f78c0-86a5-4585-b7f5-49d57582e964",
    "description": "테스트용 강의 4번 입니다!",
    "teacherId": 18
}