### Create a lecture
POST http://localhost:3010/lecture/create
content-type: application/json

{
    "title": "강의 4",
    "description": "테스트용 강의 4번 입니다!"
}

### Approve an existing lecture
PATCH http://localhost:3010/lecture/update
content-type: application/json

{
    "approved": false
}

### Query Param Test
GET http://localhost:3010/reports?~~~